#!/usr/bin/env python
# Copyright 2015 Flipkart Internet Pvt. Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import argparse
import json
import requests
import os.path
import time
import getpass
from tabulate import tabulate
from termcolor import colored
from requests.auth import HTTPBasicAuth
from requests.exceptions import ConnectionError, HTTPError
import tqdm
import warnings
import traceback

# I personally don`t like doing this :)
warnings.filterwarnings("ignore")

marathon="localhost:8080"
waitTime=10
userAuth=False
httpBasicCreds = None
protocol = "http"
httpsVerify = True

def url(path):
    return protocol + "://" + marathon + path

def endpoint_url(endpoint, path):
    return protocol + "://" + endpoint + path

def mesos_master_endpoint():
    return marathon.split(':')[0] + ':' + "5050"

def printApiError(r):
    if r.status_code == 401:
        print("Authentication error:: Check your username and password")
        return
    error=json.loads(r.text)
    try:
        if 'details' in error:
            print("Error: Marathon returned [" + str(r.status_code) + "] : " + error['message'] + ": " + error['details'])
        else:
            print("Error: Marathon returned [" + str(r.status_code) + "] : " + error['message'])
    except:
        print("Error: Marathon returned [" + str(r.status_code) + "] : " + r.text)

def printInfoTable(apps, aliveOnly=False, deadOnly=False):
    rows=[]
    for app in apps:
        if True == aliveOnly and 0 == app['tasksHealthy']:
            continue
        if True == deadOnly and 0 < app['tasksHealthy']:
            continue
        row=[]
        row.append(app['id'])
        row.append(app['cpus'])
        row.append(app['mem'])
        #row.append(app['tasksHealthy'])
        if not 'taskStats' in app or not 'totalSummary' in app['taskStats']:
            row.append(0)
            row.append(0)
            row.append(0)
            row.append(0)
            row.append(colored("DOWN", 'red'))
        else:
            taskStats=app['taskStats']['totalSummary']['stats']['counts']
            row.append(taskStats['healthy'])
            row.append(taskStats['unhealthy'])
            row.append(taskStats['running'])
            row.append(taskStats['staged'])
            row.append(colored("UP", 'green'))
        rows.append(row)
    print(tabulate(rows, headers=["App", "CPU", "Ram (MB)", "# Healthy", "# Unhealthy", "# Running", "# Deploying", "Status"], tablefmt='fancy_grid'))

def apps(aliveOnly, deadOnly):
    params = {'embed' : 'apps.taskStats'}
    r = requests.get(url("/v2/apps"), params=params, auth=httpBasicCreds, verify=httpsVerify)
    if 200 != r.status_code:
        printApiError(r)
        return
    apps = r.json()['apps']
    apps.sort(key=lambda x: x['id'])
    printInfoTable(apps, aliveOnly=aliveOnly, deadOnly=deadOnly)

def listCommand(listArgParser):
    if listArgParser.up and listArgParser.down:
        print("Both 'up' and 'down' together doesn't make sense. Are you testing me? Don't...")
        return
    apps(listArgParser.up, listArgParser.down)

def deployCommand(deployOptionsParser):
    #print(deployOptionsParser)
    configFile=deployOptionsParser.config
    if not os.path.isfile(configFile):
        print("Error: Deployment descriptor file " + configFile + " does not exist")
        return
    with open(configFile, 'r') as myfile:
        data=myfile.read()
    #requests.post(
    #print("Config: " + configFile)
    r = requests.post(url("/v2/apps"), data = data, headers = {'content-type': 'application/json'}, auth=httpBasicCreds, verify=httpsVerify)
    if r.status_code == 201:
        print("App deployment request accepted. Use list command to check")
    elif r.status_code == 409:
        print("Error: App already exists")
    else:
        printApiError(r)

def loadInstance(instance, rows):
    row = []
    row.append(instance['id'])
    row.append(instance['host'])
    row.append(', '.join([str(x) for x in instance['ports']]))
    row.append(instance['startedAt'])
    if 'healthCheckResults' in instance:
        if instance['healthCheckResults'][0]['alive'] == True:
            row.append(colored('HEALTHY', 'green'))
        else:
            row.append(colored('UNHEALTHY', 'red'))
    else:
        row.append(colored('STAGING', 'yellow'))
    rows.append(row)

def isInstanceHealthy(instance):
    return 'healthCheckResults' in instance and instance['healthCheckResults'][0]['alive'] == True

def adminEndpoint(instance):
    if 'ports' in instance and len(instance['ports']) >= 2:
        return "http://" + instance['host'] + ":" + str(instance['ports'][1])
    return None

def getAppInfo(appName):
    params = {'embed' : ['apps.taskStats', 'apps.deployments']}
    r = requests.get(url("/v2/apps/" + appName), params=params, auth=httpBasicCreds, verify=httpsVerify)
    if 200 != r.status_code:
        printApiError(r)
        return None
    return r

def scale(appName, scale, force=False):
    r = requests.put(url("/v2/apps/"+appName), data= json.dumps({'instances' : scale}), headers = {'content-type': 'application/json'}, auth=httpBasicCreds, verify=httpsVerify)
    if 200 == r.status_code:
        print("App " + appName + " scaled to " + str(scale))
    else:
        printApiError(r)

def killInstance(appName, instance, grace, rangerOOR, lbOOR, scale):
    endpoint=adminEndpoint(instance)
    if None == endpoint:
        print("No admin port info in instance: " + instance['id'])
        return

    if rangerOOR:
        oorUrl=endpoint + "/tasks/ranger-oor"
        print("Calling " + oorUrl)
        try:
            oorResponse=requests.post(oorUrl, auth=httpBasicCreds, verify=httpsVerify)
            if 200 == oorResponse.status_code or 201 == oorResponse.status_code:
                print("Took node oor on ranger")
            elif 404 == oorResponse.status_code:
                print("Ranger OOR api returned 404")
            else:
                print("Ranger OOR api returned: [" + str(oorResponse.status_code) + "] " + oorResponse.text)
                return
        except ConnectionError:
            print("Skipping connection error - exposed admin port may be invalid ?!")
            pass

    if lbOOR:
        loadbalancer_oor_url = endpoint + "/tasks/OorTask"
        print("Calling " + loadbalancer_oor_url)
        try:
            oorResponse = requests.post(loadbalancer_oor_url, auth=httpBasicCreds, verify=httpsVerify)
            if 200 == oorResponse.status_code or 201 == oorResponse.status_code:
                print("Node is oor on loadbalancer")
            elif 404 == oorResponse.status_code:
                print("Ranger OOR api returned 404")
            else:
                print("Loadbalancer OOR api returned: [" + str(
                    oorResponse.status_code) + "] !! If this is being fronted by loadbalancer, inflight calls will fail!")
        except ConnectionError:
            print("Skipping connection error - exposed admin port may be invalid ?!")
            pass

    print("Waiting for grace period: " + str(grace) + " Second(s)")
    time.sleep(grace)
    params={'scale' : scale}
    killResponse=requests.delete(url("/v2/apps/" + appName + "/tasks/" + instance['id']), params=params, auth=httpBasicCreds, verify=httpsVerify)
    if 200 == killResponse.status_code:
        print("Killed " + instance['id'])
    else:
        print("Kill api returned: [" + str(killResponse.status_code) + "] " + killResponse.text)

def destroyApp(appName, force=False):
    if not force:
        prompt_response = raw_input("Do you really want to destroy the app {0} [y/n]? ".format(appName))
    if force or prompt_response == 'y':
        r = requests.delete(url("/v2/apps/" + appName), auth=httpBasicCreds, verify=httpsVerify)
        if 200 == r.status_code:
            print("App " + appName + " destroyed")
        else:
            printApiError(r)
    else:
        print("Not destroying app {0}".format(appName))

def destroyCommand(destroyAppOptionsParser):
    appName = destroyAppOptionsParser.app
    destroyApp(appName)

def getMesosSlaveId(mesosMasterEndpoint, hostname):
    r = requests.get(endpoint_url(mesosMasterEndpoint, '/slaves'), auth=httpBasicCreds, verify=httpsVerify)
    if 200 == r.status_code:
        slaves = [slave['id'] for slave in r.json()['slaves'] if slave['hostname'] == hostname and slave['active'] == True]
        if not slaves:
            print("No matching active mesos slave with hostname {0}".format(hostname))
            return
        elif len(slaves) > 1:
            print("Multiple active mesos slaves with hostname {0}".format(hostname))
            return
        else:
            return slaves[0]

def getInstanceList(appName):
    r = getAppInfo(appName)
    if None == r:
        print("No app: " + appName)
        return
    data=r.json()
    app=data['app']
    instances = app['tasks']
    return instances

def getTaskInstance(task, filter):
    instances = getInstanceList(task['appId'])
    if filter(instances):
        return {'appName': task['appId'], 'taskId': task['id'], 'instance': task}

def decommission(mesosMasterEndpoint, hostname):
    if not mesosMasterEndpoint:
        mesosMasterEndpoint = mesos_master_endpoint()
    slaveId = getMesosSlaveId(mesosMasterEndpoint, hostname)
    if not slaveId:
        print("Cannot resolve slaveId for hostname {0}".format(hostname))
        return
    prompt_response = raw_input("Do you really want to decommission node with hostname = {0}, slaveId = {1} [y/n]? ".format(hostname, slaveId))
    if prompt_response != 'y':
        print("Not going to decommission")
        return
    r = requests.get(url("/v2/tasks"), auth=httpBasicCreds, verify=httpsVerify)
    if 200 != r.status_code:
        print("Tasks API errored out - returned: [" + str(r.status_code) + "] " + r.text)

    print("Fetching list of tasks that need to be killed....")
    tasks_on_slave = sorted([task for task in r.json()['tasks'] if task['slaveId'] == slaveId])
    candidate_tasks = sorted([getTaskInstance(task, lambda l: len(l) > 1) for task in tasks_on_slave])
    skipped_tasks = [getTaskInstance(task, lambda l: len(l) == 1) for task in tasks_on_slave if task not in candidate_tasks]
    candidate_tasks = [task for task in candidate_tasks if task is not None]
    skipped_tasks = [task for task in skipped_tasks if task is not None]
    failures = []
    if skipped_tasks:
        print("Skipping suspend of following apps because they are running with only one instance \n{0}"
            .format("\n".join(set([task['appName'] for task in skipped_tasks]))))
        print("Cannot proceed further unless these apps are scaled up.... Exiting")
        exit(1)
    for task in tqdm.tqdm(candidate_tasks):
        print("Killing app = {0}, instance = {1}".format(task['appName'], task['taskId']))
        try:
            killInstance(appName=task['appName'], instance=task['instance'], grace=30, rangerOOR=True, lbOOR=True, scale=True)
        except KeyboardInterrupt:
            print("Received <CTRL-C> stopping everything")
            exit(1)
        except:
            print("Failed to kill app = {0}, instance = {1}".format(task['appName'], task['taskId']))
            print(traceback.format_exc())
            exit(1)
            #failures.append({'appName': task['appName'], 'taskId': task['taskId']})
    if failures:
        print("Failed to properly suspend the following tasks \n{0}".format("\n".join([task['taskId'] for task in failures])))


def decommissionCommand(decommissionClusterOptionsParser):
    decommission(decommissionClusterOptionsParser.mesos_endpoint, decommissionClusterOptionsParser.hostname)

def waitForTargetScale(appName, targetScale):
    while True:
        r = getAppInfo(appName)
        if None == r:
            print("No app: " + appName)
            exit(1)
        data=r.json()
        app=data['app']
        instances = app['tasks']
        healthy = 0
        for instance in instances:
            if isInstanceHealthy(instance):
                healthy += 1
        if healthy == targetScale:
            print("Target scale factor reached: " + str(targetScale))
            return
        else:
            print("Current scale factor: " + str(healthy) + " Target: " + str(targetScale))
        time.sleep(3)

def restartCommand(restartOptionsParser):
    appName = restartOptionsParser.app
    grace = restartOptionsParser.grace
    lbOOR = restartOptionsParser.lboor
    rangerOOR = restartOptionsParser.rangeroor
    r = getAppInfo(appName)
    if None == r:
        print("Error: No such app:" + appName)
        return
    data=r.json()
    app=data['app']
    instances = app['tasks']
    if 0 == len(instances):
        print("There are no running instances. Use 'scale' to scale up")
        return
    targetScale=len(instances)
    if restartOptionsParser.noScaling == False:
        targetScale=len(instances) + 1
        scale(appName, targetScale)
        waitForTargetScale(appName, targetScale)
    for instance in instances:
        killInstance(appName, instance, grace, rangerOOR, lbOOR, False)
        time.sleep(2)
        waitForTargetScale(appName, targetScale)
        print("Instance " + instance['id'] + " replaced")
    if restartOptionsParser.noScaling == False:
        scale(appName, targetScale - 1)
        waitForTargetScale(appName, targetScale - 1)
    print("App restarted")

def infoCommand(infoOptionsParser):
    r = getAppInfo(infoOptionsParser.app)
    if None == r:
        print("Error: No such app:" + infoOptionsParser.app)
        return
    data=r.json()
    app=data['app']
    printInfoTable([app])
    if not 'taskStats' in app or not 'totalSummary' in app['taskStats']:
        print("App is down")
    else:
        rows = []
        for instance in app['tasks']:
            loadInstance(instance, rows)
        print(tabulate(rows, headers=["Instance", "host", "Ports", "Started", "Status"], tablefmt='fancy_grid'))
        rows=[]
        for deployment in app['deployments']:
            rows.append([deployment['id']])
        if len(rows) > 0:
            print(tabulate(rows, headers=["Deployment ID"], tablefmt='fancy_grid'))


def scaleCommand(scaleOptionsParser):
    appName = scaleOptionsParser.app
    grace = scaleOptionsParser.grace
    lbOOR = scaleOptionsParser.lboor
    rangerOOR = scaleOptionsParser.rangeroor
    r = getAppInfo(appName)
    if None == r:
        print("Error: No such app:" + appName)
        return
    data=r.json()
    app=data['app']
    instances = app['tasks']
    instanceCount=scaleOptionsParser.instances
    currentInstances=len(instances)
    if instanceCount == currentInstances:
        print("Nothing to do. Already at: " + str(currentInstances))
        return
    for instance in instances:
        if instanceCount >= currentInstances:
            break
        killInstance(appName, instance, grace, rangerOOR, lbOOR, True)
        time.sleep(2)
        currentInstances = currentInstances - 1
        print("Instance " + instance['id'] + " stop requested")
    scale(appName, instanceCount)
    waitForTargetScale(appName, instanceCount)

def suspendCommand(suspendOptionsParser):
    appName = suspendOptionsParser.app
    grace = suspendOptionsParser.grace
    lbOOR = suspendOptionsParser.lboor
    rangerOOR = suspendOptionsParser.rangeroor
    destroy = suspendOptionsParser.destroy
    r = getAppInfo(appName)
    if None == r:
        print("Error: No such app:" + appName)
        return
    data=r.json()
    app=data['app']
    instances = app['tasks']
    currentInstances = len(instances)
    keyboard_response = raw_input("Commencing suspend operation.... Are you sure [y/n]? ")
    if keyboard_response == 'y':
        for instance in instances:
            killInstance(appName, instance, grace, rangerOOR, lbOOR, True)
            time.sleep(2)
            currentInstances = currentInstances - 1
        waitForTargetScale(appName, 0)
        if destroy:
            destroyApp(appName, force=True)


def killSingleAppInstance(killSingleAppConfig):
    appName = killSingleAppConfig.app
    instanceId = killSingleAppConfig.instance
    grace = killSingleAppConfig.grace
    lbOOR = killSingleAppConfig.lboor
    rangerOOR = killSingleAppConfig.rangeroor
    r = getAppInfo(appName)
    if None == r:
        print("Error: No such app:" + appName)
        return
    data=r.json()
    app=data['app']
    instances = app['tasks']
    candidateInstance = None
    for instance in instances:
        if instance['id'] == instanceId:
            candidateInstance = instance
            break
    if candidateInstance == None:
        print("Error: Invalid instance ID: " + instanceId)
    currentInstances=len(instances)
    killInstance(appName, instance, grace, rangerOOR, lbOOR, True)
    waitForTargetScale(appName, currentInstances - 1)

def getUserPassword():
    password = getpass.getpass(prompt='Password: ', stream=None)
    return password

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Marathon apps manager. Named after main character in Marathon Man.')
    parser.add_argument('-e', '--endpoint', help='Marathon host:port', default="localhost:8080", required=True)
    parser.add_argument('-p', '--protocol', help='Protocol for Marathon endpoint', choices=['http','https'], default="http")
    parser.add_argument('-k', '--ssl-insecure', help='Skip SSL Check', dest='sslVerify', action='store_false')
    parser.add_argument('-U', '--user', help='HTTP Basic authentication username ( password will be asked via prompt )', default="", required=False)

    subparsers = parser.add_subparsers(help='Available operations')

    #List
    listOptionsParser = subparsers.add_parser('list', help='List running apps')
    listOptionsParser.add_argument('-u', '--up', help='Show only apps that are alive', action='store_true')
    listOptionsParser.add_argument('-d', '--down', help='Show only apps that are dead', action='store_true')
    listOptionsParser.set_defaults(func=listCommand)

    #Info
    infoOptionsParser = subparsers.add_parser('info', help='Info about a running app')
    infoOptionsParser.add_argument('app', help='App name')
    infoOptionsParser.set_defaults(func=infoCommand)

    #Deploy
    deployOptionsParser = subparsers.add_parser('deploy', help='Deploy an app')
    deployOptionsParser.add_argument('-c' , '--config', help='Deployment json descriptor', required=True)
    deployOptionsParser.set_defaults(func=deployCommand)

    #Restart
    restartOptionsParser = subparsers.add_parser('restart', help='Restart an app')
    restartOptionsParser.add_argument('app', help='App name')
    restartOptionsParser.add_argument('-g', '--grace', help='Grace period to sleep for before killing the process', type=int, default=30)
    restartOptionsParser.add_argument('-n', '--no-scaling', help="Don't scale up the app before killing the processs", dest='noScaling', action='store_true')
    restartOptionsParser.add_argument('-l', '--lb-oor', help='Whether to take it OOR in load balancer as well', dest='lboor', action='store_true')
    restartOptionsParser.add_argument('-r', '--ranger-oor', help='Whether to take it OOR in ranger as well', dest='rangeroor', action='store_false')
    restartOptionsParser.set_defaults(func=restartCommand)

    #Scale
    scaleOptionsParser = subparsers.add_parser('scale', help='Scale an app')
    scaleOptionsParser.add_argument('app', help='App name')
    scaleOptionsParser.add_argument('-n', '--instances', help='Number of instances required. This number is absolute.', type=int, required=True)
    scaleOptionsParser.add_argument('-g', '--grace', help='Grace period to sleep for before killing the process', type=int, default=35)
    scaleOptionsParser.add_argument('-l', '--lb-oor', help='Whether to take it OOR in load balancer as well', dest='lboor', action='store_true')
    scaleOptionsParser.add_argument('-r', '--ranger-oor', help='Whether to take it OOR in ranger as well', dest='rangeroor', action='store_false')
    scaleOptionsParser.set_defaults(func=scaleCommand)

    #Suspend
    suspendOptionsParser = subparsers.add_parser('suspend', help='Suspend an app (equivalent to scale=0)')
    suspendOptionsParser.add_argument('app', help='App name')
    suspendOptionsParser.add_argument('-g', '--grace', help='Grace period to sleep for before killing the process', type=int, default=35)
    suspendOptionsParser.add_argument('-l', '--lb-oor', help='Whether to take it OOR in load balancer as well', dest='lboor', action='store_true')
    suspendOptionsParser.add_argument('-r', '--ranger-oor', help='Whether to take it OOR in ranger as well', dest='rangeroor', action='store_false')
    suspendOptionsParser.add_argument('-d', '--destroy', help='If this flag is set, then the app will be destroyed after suspension if it has zero instances running', dest='destroy', action='store_true', default=False)
    suspendOptionsParser.set_defaults(func=suspendCommand)

    #Kill Instance
    killInstanceOptionsParser = subparsers.add_parser('kill', help='Kill an app instance')
    killInstanceOptionsParser.add_argument('app', help='App name')
    killInstanceOptionsParser.add_argument('-i', '--instance', help='Instance ID to be killed', required=True)
    killInstanceOptionsParser.add_argument('-g', '--grace', help='Grace period to sleep for before killing the process', type=int, default=35)
    killInstanceOptionsParser.add_argument('-l', '--lb-oor', help='Whether to take it OOR in load balancer as well', dest='lboor', action='store_true')
    killInstanceOptionsParser.add_argument('-r', '--ranger-oor', help='Whether to skip taking instance OOR in ranger', dest='rangeroor', action='store_false')
    killInstanceOptionsParser.set_defaults(func=killSingleAppInstance)

    #Destroy App
    destroyAppOptionsParser = subparsers.add_parser('destroy', help='Destroy an app instance')
    destroyAppOptionsParser.add_argument('app', help='App name')
    destroyAppOptionsParser.set_defaults(func=destroyCommand)

    #Decommission Cluster
    decommissionClusterOptionsParser = subparsers.add_parser('decommission', help='Decommission a Mesos slave')
    decommissionClusterOptionsParser.add_argument('-m', '--mesos-endpoint', help='Mesos master host:port', dest='mesos_endpoint')
    decommissionClusterOptionsParser.add_argument('-n', '--hostname', help='Hostname of Mesos slave that needs to be decommissioned', default='localhost', required=True)
    decommissionClusterOptionsParser.set_defaults(func=decommissionCommand)

    parsed=parser.parse_args()
    marathon=parsed.endpoint
    useAuth = len(parsed.user) > 0
    if useAuth == True:
        password = getUserPassword()
        httpBasicCreds = HTTPBasicAuth(parsed.user, password)
    httpsVerify = parsed.sslVerify
    protocol = parsed.protocol
    parsed.func(parsed)
